# 使用适合您的M1芯片的基础Linux镜像
FROM openjdk:17-jdk

# /tmp 目录就会在运行时自动挂载为匿名卷，任何向 /tmp 中写入的信息都不会记录进容器存储层
VOLUME /tmp

ADD target/youlai-boot.jar app.jar

CMD java \
    -Djava.security.egd=file:/dev/./urandom \
    -jar /app.jar

EXPOSE 8989